### ISSUE TITLE
`.min.js` empty!

### ISSUE THREAD

**Issue by lil5** [finwo/js-notify-sl#4]
Run a build before publishing to npm: see `prepublishOnly` in https://docs.npmjs.com/misc/scripts

**Comment by finwo** [comment]
I'm sorry to say that I completely missed it.
Fixed the unstable build by replacing [uglify](https://npmjs.com/package/uglify) with [uglify-js](https://npmjs.com/package/uglify-js).

Implemented your suggestion as well, so the automatic deploy after testing now ensures a build as well.
